# -*- coding: utf-8 -*-
"""topsis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QJODYXTTw83NzDInKxhQFRoRCUXk_FLN
"""

import numpy as np
import pandas as pd

data = pd.DataFrame({
    "Accuracy": [0.92, 0.94, 0.90, 0.91, 0.93],
    "F1-score": [0.91, 0.93, 0.89, 0.90, 0.92],
    "Inference Time": [45, 50, 25, 30, 55],
    "Model Size": [420, 500, 250, 220, 480],
    "Training Time": [6, 7, 4, 5, 8]
}, index=["BERT", "RoBERTa", "DistilBERT", "ALBERT", "XLNet"])

weights = np.array([0.30, 0.25, 0.20, 0.15, 0.10])

normalized = data / np.sqrt((data ** 2).sum())

weighted = normalized * weights

ideal_best = weighted.max()
ideal_worst = weighted.min()

distance_best = np.sqrt(((weighted - ideal_best) ** 2).sum(axis=1))
distance_worst = np.sqrt(((weighted - ideal_worst) ** 2).sum(axis=1))

topsis_score = distance_worst / (distance_best + distance_worst)

result = pd.DataFrame({
    "TOPSIS Score": topsis_score,
    "Rank": topsis_score.rank(ascending=False)
})

print(result.sort_values("Rank"))